### ISSUE TITLE
Installation not very clear

### ISSUE THREAD

**Issue by miketheman** [jterrace/sphinxtr#40]
Hello!

In attempting to start using your libraries, there are no formal packages, making it not possible to either `pip install sphinxtr` from PyPI, nor using the direct source from GitHub, as there is no `setup.py` package either.
These would be helpful to get the package installed and usable quickly.

Here's a reference on Python packaging: http://python-packaging-user-guide.readthedocs.io/en/latest/distributing/

**Comment by jterrace** [comment]
Making it a package doesn't really make sense in this case. The expected way to use the project is to fork it and write your own text.

**Comment by miketheman** [comment]
I see. That's not entirely clear from the README, but I understand.

**Comment by jterrace** [comment]
I agree the docs could be more clear. Opening back up to update the README

**Comment by ijstokes** [comment]
The main question I have is how to incorporate this into an existing Sphinx-based documentation set.  I would love to use some of the features here, but I just don't know how to do that.

**Comment by miketheman** [comment]
Closing some of my older open issues.
